"""Add webhook name, event_types JSON, and test tracking fields

Revision ID: fa27f172aa6d
Revises: 15d947c3ae18
Create Date: 2025-11-19 08:27:22.759537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa27f172aa6d'
down_revision = '15d947c3ae18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('event_types', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('last_test_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_test_response_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_test_response_time', sa.Float(), nullable=True))
        batch_op.drop_column('event_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_column('last_test_response_time')
        batch_op.drop_column('last_test_response_code')
        batch_op.drop_column('last_test_status')
        batch_op.drop_column('event_types')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
